services:
  cdb-control-plane:
    image: ${ECR_IMAGE_URI}
    container_name: cdb-control-plane
    restart: unless-stopped
    environment:
      CONTROL_PLANE_PORT: ${CONTROL_PLANE_PORT}
      AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_REPLICA_AMI_ID: ${AWS_REPLICA_AMI_ID}
      AWS_REPLICA_INSTANCE_TYPE: ${AWS_REPLICA_INSTANCE_TYPE}
      AWS_REPLICA_SUBNET_ID: ${AWS_REPLICA_SUBNET_ID}
      AWS_REPLICA_IAM_INSTANCE_PROFILE_NAME: ${AWS_REPLICA_IAM_INSTANCE_PROFILE_NAME}
      AWS_REPLICA_TX_MANAGER_PORT: ${AWS_REPLICA_TX_MANAGER_PORT}
      AWS_REPLICA_TX_MANAGER_SECURITY_GROUP_ID: ${AWS_REPLICA_TX_MANAGER_SECURITY_GROUP_ID}
      AWS_REDIS_STORAGE_ENGINE_PORT: ${AWS_REDIS_STORAGE_ENGINE_PORT}
      AWS_REDIS_STORAGE_ENGINE_SECURITY_GROUP_ID: ${AWS_REDIS_STORAGE_ENGINE_SECURITY_GROUP_ID}
      AWS_REPLICA_APPLIER_PORT: ${AWS_REPLICA_APPLIER_PORT}
      AWS_REPLICA_APPLIER_SECURITY_GROUP_ID: ${AWS_REPLICA_APPLIER_SECURITY_GROUP_ID}
      CDB_CHRONICLE_SERVICE_IP: ${CDB_CHRONICLE_SERVICE_IP}
      CDB_CHRONICLE_SERVICE_PORT: ${CDB_CHRONICLE_SERVICE_PORT}
      CDB_CHRONICLE_LOG_KAFKA_BOOTSTRAP_SERVERS: ${CDB_CHRONICLE_LOG_KAFKA_BOOTSTRAP_SERVERS}
    ports:
      - "${CONTROL_PLANE_PORT}:${CONTROL_PLANE_PORT}"