services:
  cdb-control-plane:
    image: ${ECR_IMAGE_URI}
    container_name: cdb-control-plane
    restart: unless-stopped
    environment:
      CONTROL_PLANE_PORT: ${CONTROL_PLANE_PORT}
      AWS_REGION: ${AWS_REGION}
      AWS_REPLICA_AMI_ID: ${AWS_REPLICA_AMI_ID}
      AWS_REPLICA_INSTANCE_TYPE: ${AWS_REPLICA_INSTANCE_TYPE}
      AWS_REPLICA_SUBNET_ID: ${AWS_REPLICA_SUBNET_ID}
      AWS_REPLICA_SECURITY_GROUP_ID: ${AWS_REPLICA_SECURITY_GROUP_ID}
    ports:
      - "${CONTROL_PLANE_PORT}:${CONTROL_PLANE_PORT}"