server.port=${CONTROL_PLANE_PORT}
aws.region=${AWS_REGION}
aws.replica.ami-id=${AWS_REPLICA_AMI_ID}
aws.replica.instance-type=${AWS_REPLICA_INSTANCE_TYPE}
aws.replica.subnet-id=${AWS_REPLICA_SUBNET_ID}
aws.replica.redis-tx-manager-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.redis-storage-engine-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.redis-applier-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.iam-instance-profile-name=${AWS_REPLICA_IAM_INSTANCE_PROFILE_NAME}
spring.jackson.serialization.write-dates-as-timestamps=false