aws.region=us-east-1
aws.dynamodb.tables.users=users
aws.dynamodb.tables.chronicles=chronicles
aws.dynamodb.gsi.users-by-hashed-api-key=users-by-hashed-api-key
spring.jackson.serialization.write-dates-as-timestamps=false