server.port=${CONTROL_PLANE_PORT}
spring.jackson.serialization.write-dates-as-timestamps=false

aws.account-id=${AWS_ACCOUNT_ID}
aws.region=${AWS_REGION}

aws.replica.redis.ami-id=${AWS_REPLICA_AMI_ID}
aws.replica.redis.instance-type=${AWS_REPLICA_INSTANCE_TYPE}
aws.replica.redis.subnet-id=${AWS_REPLICA_SUBNET_ID}
aws.replica.redis.tx-manager-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.redis.storage-engine-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.redis.applier-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.redis.iam-instance-profile-name=${AWS_REPLICA_IAM_INSTANCE_PROFILE_NAME}

aws.replica.postgresql.ami-id=${AWS_REPLICA_AMI_ID}
aws.replica.postgresql.instance-type=${AWS_REPLICA_INSTANCE_TYPE}
aws.replica.postgresql.subnet-id=${AWS_REPLICA_SUBNET_ID}
aws.replica.postgresql.tx-manager-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.postgresql.storage-engine-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.postgresql.applier-security-group-id=${AWS_REPLICA_SECURITY_GROUP_ID}
aws.replica.postgresql.iam-instance-profile-name=${AWS_REPLICA_IAM_INSTANCE_PROFILE_NAME}

cdb.chronicle.service.ip=${CDB_CHRONICLE_SERVICE_IP}
cdb.chronicle.service.port=${CDB_CHRONICLE_SERVICE_PORT}